### ISSUE TITLE
Can't identify devices in Windows

### ISSUE THREAD

**Issue by djrobx** [NoobsArePeople2/manymouse#1]
This API is terrific, but currently the mouse enumeration sample gives this on my system.  Not very useful at identifying which device is which:

#0: HID-compliant mouse
#1: HID-compliant mouse
#2: HID-compliant mouse
#3: HID-compliant mouse
#4: HID-compliant mouse
#5: HID-compliant mouse
#6: HID-compliant mouse
#7: Unidentified input device
#8: Unidentified input device

By changing SPDRP_DEVICEDESC to SPDRP_HARDWAREID in get_dev_name_by_instance(...) in windows_wmpint.c, the devices now have much more useful hardware IDs that I can use to distinguish them:

#0: HID\VID_D209&PID_1501&REV_0038&MI_03&Col02
#1: HID\VID_D209&PID_1501&REV_0038&MI_03&Col01
#2: HID\VID_046D&PID_C52E&REV_1500&MI_01&Col01
#3: HID\VID_D209&PID_1502&REV_0037&MI_03&Col02
#4: HID\VID_D209&PID_1502&REV_0037&MI_03&Col01
#5: HID\VID_D209&PID_1503&REV_0037&MI_03&Col02
#6: HID\VID_D209&PID_1503&REV_0037&MI_03&Col01
#7: Unidentified input device
#8: Unidentified input device

Now it's possible to identify a specific controller consistently regardless of enumeration order.  I suggest making this change or adding another "GetHardwareID" function to make this possible officially.

**Comment by NoobsArePeople2** [comment]
I didn't write this library, I just put a mirror of it up here so unfortunately I won't be able to you out.

Check here for contact info: http://hg.icculus.org/icculus/manymouse/
